spring.application.name=casa-de-oxala-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/casadeoxala}
spring.datasource.username=${DB_USERNAME:casadeoxala}
spring.datasource.password=${DB_PASSWORD:casadeoxala}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
